import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import Sidebar from "./_sidebar/sidebar";
import Navbar from "./_navbar/navbar";
import { getServerAuthSession } from "@/server/auth";
import AuthSessionProvider from "../../components/providers/session-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
    >
      <body className="grid-cols-[auto,1fr] md:grid">
        <AuthSessionProvider session={session}>
          <TRPCReactProvider>
            <aside className="hidden md:flex">
              <Sidebar />
            </aside>
            <div className="grid h-full grid-rows-[auto,1fr]">
              <Navbar />
              {children}
            </div>
          </TRPCReactProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
