import { type Metadata } from "next";

import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";

import AuthSessionProvider from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/toaster";

import { auth } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";

import Navbar from "./_navbar/navbar";
import Sidebar from "./_sidebar/sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
    >
      <body>
        <main className="grid h-full md:grid-cols-[auto,1fr]">
          <AuthSessionProvider session={session}>
            <TRPCReactProvider>
              <aside className="hidden h-full md:flex">
                <Sidebar />
              </aside>
              <div className="grid h-full grid-rows-[auto,1fr]">
                <Navbar />
                {children}
              </div>
            </TRPCReactProvider>
          </AuthSessionProvider>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
