import { type Metadata } from "next";

import { env } from "@/env";
import "@/styles/globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { GeistSans } from "geist/font/sans";

import AuthSessionProvider from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/toaster";

import { auth } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
    >
      <body>
        <AuthSessionProvider session={session}>
          <TRPCReactProvider>
            {children}
            {env.NODE_ENV !== "production" && (
              <ReactQueryDevtools initialIsOpen={false} />
            )}
          </TRPCReactProvider>
        </AuthSessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
